#!/bin/bash
git config --global credential.helper 'cache --timeout=14400'
git config --global user.name "Adil Qadimaliyev"
git config --global user.email "13153@holbertonstudents.com"
cd holbertonschool-unix || exit
